sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "hsSfNQD7H9EnVj66rolv5gl7+OVro0SV6Sg9awqIvk0apl8urD/sLsIuxcNTBk9os+BzMWuRtu9hjuhFejns2eXRbKmLaMAbZnvdAs5XovbrCcdvWxexg8hsQ77anMtV1m1GEpJ1OMp1gCLNFj0KEwv7/frTaw5Ru4F6XqOG1NmhUHNO8lLZ33SG3GYPLOtcOvmVKPH9AKOl8MujIAlvKri6sSZHfaf1+b+qzeDOxFPOiOcrl01DeQZOWljvJnZxXC3jPsAagI893tx6FwmokWmDVNaLHltNXq+Nd0rKSVu5OyzRYrcty6jCtKm2LYPhD7SiL7/F7W5+30WVsfj1JC7RCMq5DbStpsRELT1IGdPI2U/V7azCdUqwlhm+mxrOz0tKZMEoTGs445w5xwemdMkDBioDLqXKB77MGYGtTi+xNjaPvvE/OH45vlWYRP0oBx3/zh2Kxy6OD/uQm4lUsPfHdbzch63aev0xYMtLPtsvOpQvGx0uwT/P/VFKrLQ829CU8DdRkN3LkQCjoveay2kePp8Qs4mCZnsH4meFuxlemq7gwNpsDC/ueJNN9Y0DaDBpQgqpc3o9BvE2CtgxyZUAet8M9N/uqn6lCARwdQgzOs9WqcxTQGqoeaj+Gxz2eXyhXDIE72EupgRCf4DhOCLvtd3Yb9A2sKAQSWVYJd4="
  only:
    - master
